grafana:
    image: grafana-test
    ports: 
        - 3012:3000
    links:
        - influxdb:influxdb
    environment:
        GF_INSTALL_PLUGINS: abhisant-druid-datasource
        GF_SECURITY_ADMIN_USER: admin
        GF_SECURITY_ADMIN_PASSWORD: admin
        GF_SECURITY_SECRET_KEY: grafana
        GF_USERS_ALLOW_SIGN_UP: 'true'
        GF_USERS_ALLOW_ORG_CREATE: 'true'
        GF_AUTH_ANONYMOUS_ENABLED: 'true'
        GF_AUTH_ANONYMOUS_ORG_NAME: grafana
        GF_DASHBOARDS_JSON_ENABLED: 'true'
        GF_DASHBOARDS_JSON_PATH: /opt/grafana
    labels:
        io.rancher.sidekicks: grafana-data
    volumes_from:
        - grafana-data

grafana-data:
    image: busybox
    tty: true
    volumes:
        - /var/lib/grafana
        - /var/log/grafana
        - /var/lib/grafana/plugins

influxdb:
    image: influxdb-test
    ports:
        - 8183:8083
        - 8186:8086
    environment:
        INFLUX_DATABASE: "telegraf"
        INLFUX_ADMIN_USER: "grafana"
        INFLUX_ADMIN_PASS: "grafana"
    volumes_from:
        - influxdb-data

influxdb-data:
    image: busybox
    tty: true
    volumes:
        - /var/lib/influxdb

telegraf:
    image: telegraf-test
    links:
        - influxdb:influxdb
    environment:
        HOST_NAME: "telegraf"
        INFLUXDB_HOST: "influxdb"
        INFLUXDB_PORT: "8086"
        DATABASE: "telegraf"
    tty: true
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

