grafana:
    image: matisq/grafana
    ports: 
        - ${grafana_port}:3000
    links:
        - influxdb:influxdb
    environment:
        GF_INSTALL_PLUGINS: abhisant-druid-datasource
        GF_SECURITY_ADMIN_USER: admin
        GF_SECURITY_ADMIN_PASSWORD: admin
        GF_SECURITY_SECRET_KEY: grafana
        GF_USERS_ALLOW_SIGN_UP: "true"
        GF_USERS_ALLOW_ORG_CREATE: "true"
        GF_AUTH_ANONYMOUS_ENABLED: "true"
        GF_AUTH_ANONYMOUS_ORG_NAME: grafana
        GF_DASHBOARDS_JSON_ENABLED: "true"
        GF_DASHBOARDS_JSON_PATH: /opt/grafana
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
    labels:
        io.rancher.sidekicks: grafana-data
    volumes_from:
        - grafana-data

grafana-data:
    image: busybox
    tty: true
    volumes:
        - /var/lib/grafana
        - /var/log/grafana
        - /var/lib/grafana/plugins

influxdb:
    image: matisq/influxdb
    ports:
        - ${influx_ui}:8083
        - ${influx_db}:8086
    environment:
        INFLUX_DATABASE: "telegraf"
        INLFUX_ADMIN_USER: "grafana"
        INFLUX_ADMIN_PASS: "grafana"
    labels:
        io.rancher.sidekicks: influxdb-data
    volumes_from:
        - influxdb-data

influxdb-data:
    image: busybox
    tty: true
    volumes:
        - /var/lib/influxdb

telegraf:
    image: matisq/telegraf
    links:
        - influxdb:influxdb
    environment:
        HOST_NAME: "telegraf"
        INFLUXDB_HOST: "influxdb"
        INFLUXDB_PORT: "8086"
        DATABASE: "telegraf"
    tty: true
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

